name = "Hasper"
license = "MIT"
licenselink = "https://raw.githubusercontent.com/dencold/hasper/master/LICENSE"
description = "Casper theme from Ghost Foundation, ported to Hugo"
homepage = "https://github.com/dencold/hasper"
tags = ["blog"]
features = ["disqus", "google analytics","share"]
min_version=0.14

[author]
  name = "Dennis Coldwell"
  homepage = "http://dencold.com"

[original]
  name = "Valere JEANTET"
  homepage = "http://vjeantet.fr/"
  repo = "https://github.com/vjeantet/hugo-theme-casper"
